import Foundation
import Testing

@testable import Fathom

/// Pins the Swift WordPiece tokenizer to the HuggingFace reference tokenizer:
/// `tokenizer_fixtures.json` is generated by tools/embedding-model/convert.py
/// from the exact `bge-small-en-v1.5` tokenizer the Core ML model was
/// converted with. Any drift here silently corrupts every embedding.
struct WordPieceTokenizerTests {

    private struct Fixtures: Decodable {
        struct Case: Decodable {
            let text: String
            let inputIDs: [Int32]
            let attentionMask: [Int32]

            enum CodingKeys: String, CodingKey {
                case text
                case inputIDs = "input_ids"
                case attentionMask = "attention_mask"
            }
        }
        let seqLen: Int
        let cases: [Case]

        enum CodingKeys: String, CodingKey {
            case seqLen = "seq_len"
            case cases
        }
    }

    private static func loadTokenizer() throws -> WordPieceTokenizer {
        let vocabURL = try #require(
            Bundle.main.url(forResource: "bge_vocab", withExtension: "txt"),
            "bge_vocab.txt missing from app bundle"
        )
        return try WordPieceTokenizer(vocabFileURL: vocabURL)
    }

    private static func loadFixtures() throws -> Fixtures {
        final class Token {}
        let url = try #require(
            Bundle(for: Token.self).url(forResource: "tokenizer_fixtures", withExtension: "json"),
            "tokenizer_fixtures.json missing from test bundle"
        )
        return try JSONDecoder().decode(Fixtures.self, from: Data(contentsOf: url))
    }

    @Test func matchesHuggingFaceReference() throws {
        let tokenizer = try Self.loadTokenizer()
        let fixtures = try Self.loadFixtures()
        #expect(fixtures.seqLen == WordPieceTokenizer.sequenceLength)

        for testCase in fixtures.cases {
            let encoded = tokenizer.encode(testCase.text)
            #expect(
                encoded.inputIDs == testCase.inputIDs,
                "input_ids mismatch for: \"\(testCase.text)\""
            )
            #expect(
                encoded.attentionMask == testCase.attentionMask,
                "attention_mask mismatch for: \"\(testCase.text)\""
            )
        }
    }

    @Test func outputIsAlwaysFixedLength() throws {
        let tokenizer = try Self.loadTokenizer()
        let long = String(repeating: "disambiguation ", count: 200)
        for text in ["", "a", long] {
            let encoded = tokenizer.encode(text)
            #expect(encoded.inputIDs.count == WordPieceTokenizer.sequenceLength)
            #expect(encoded.attentionMask.count == WordPieceTokenizer.sequenceLength)
        }
    }
}
